"""Insert initial data into topics and topic_keywords

Revision ID: ea48d9771bd9
Revises: a12ef6bcf1c4
Create Date: 2024-11-02 13:03:10.905647

"""
from datetime import datetime
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea48d9771bd9'
down_revision: Union[str, None] = 'a12ef6bcf1c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    topics_table = sa.Table(
        'topics',
        sa.MetaData(),
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('created_date', sa.DateTime(), nullable=True),
    )

    topic_keywords_table = sa.Table(
        'topic_keywords',
        sa.MetaData(),
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('topic_id', sa.Integer(), nullable=False),
        sa.Column('value', sa.String(length=100), nullable=False),
    )

    connection = op.get_bind()

    connection.execute(
        topics_table.insert(),
        [
            {'name': 'Проспорт', 'created_date': datetime.utcnow()},
            {'name': 'Війна', 'created_date': datetime.utcnow()},
            {'name': 'Світ', 'created_date': datetime.utcnow()},
            {'name': 'Шоу-бізнес', 'created_date': datetime.utcnow()},
            {'name': 'Гламур', 'created_date': datetime.utcnow()},
            {'name': 'Київ', 'created_date': datetime.utcnow()},
            {'name': 'Укрaїнa', 'created_date': datetime.utcnow()},
            {'name': 'Ексклюзив ТСН', 'created_date': datetime.utcnow()},
            {'name': 'Зірки', 'created_date': datetime.utcnow()},
            {'name': 'Суспільство', 'created_date': datetime.utcnow()},
            {'name': 'Цікaвинки', 'created_date': datetime.utcnow()},
            {'name': 'Гроші', 'created_date': datetime.utcnow()},
            {'name': 'Наука та IT', 'created_date': datetime.utcnow()},
            {'name': 'Здоровий спосіб життя', 'created_date': datetime.utcnow()},
            {'name': 'Дім', 'created_date': datetime.utcnow()},
            {'name': 'Схуднення', 'created_date': datetime.utcnow()},
            {'name': 'Актуальна тема', 'created_date': datetime.utcnow()},
            {'name': 'Рецепти', 'created_date': datetime.utcnow()},
            {'name': 'Астрологія', 'created_date': datetime.utcnow()},
            {'name': 'Різне', 'created_date': datetime.utcnow()},
            {'name': 'Зброя', 'created_date': datetime.utcnow()},
            {'name': 'Корисні статті', 'created_date': datetime.utcnow()},
            {'name': 'Діти', 'created_date': datetime.utcnow()},
            {'name': 'Політика', 'created_date': datetime.utcnow()},
            {'name': 'Здоров’я', 'created_date': datetime.utcnow()},
            {'name': 'Салон краси', 'created_date': datetime.utcnow()},
            {'name': 'Львів', 'created_date': datetime.utcnow()}
        ]
    )

    topics = connection.execute(
        sa.select(topics_table.c.id, topics_table.c.name)
    ).fetchall()
    topic_id_map = {topic.name: topic.id for topic in topics}

    connection.execute(
        topic_keywords_table.insert(),
        [
            {'topic_id': topic_id_map['Проспорт'], 'value': 'челсі'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'фк рома'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'лівий берег'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'мобілізація'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'золотий мʼяч'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'динамо київ'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'зоря луганськ'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'збірна португалії'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'фк оболонь'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'ірина геращенко'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'суарес'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'фк жирона'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'ювентус'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'манчестер юнайтед'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'шахтар донецьк'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'збірна хорватії'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'легка атлетика'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'фк кривбас'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'збірна італії'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'фк ліверпуль'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'збірна уругваю'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'France Football'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'футбол'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'баварія мюнхен'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'ЛНЗ'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'кріштіану роналду'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'бундесліга'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'магучіх'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'хокей'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'молодіжна збірна україни'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'чемпіонат іспанії'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'реал мадрид'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'верес рівне'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'діамантова ліга'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'збірна україни з хокею'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'ліга націй'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'ТЦК'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'довбик'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'УПЛ'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'бетіс'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'віктор циганков'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'лаціо'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'андрій лунін'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'US Open'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'фк мілан'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'збірна франції'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'фрайбург'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'фк севілья'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'теніс'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'стрибки у висоту'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'Паралімпіада'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'людмила кіченок'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'збірна україни'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'серія А'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'мудрик'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'АПЛ'},
            {'topic_id': topic_id_map['Проспорт'], 'value': 'крістал пелас'},
            {'topic_id': topic_id_map['Війна'], 'value': 'інститут'},
            {'topic_id': topic_id_map['Війна'], 'value': 'Ту-22МЗ'},
            {'topic_id': topic_id_map['Війна'], 'value': 'авіаудар'},
            {'topic_id': topic_id_map['Війна'], 'value': 'стрес'},
            {'topic_id': topic_id_map['Війна'], 'value': 'новини Львова'},
            {'topic_id': topic_id_map['Війна'], 'value': 'психотерапевт'},
            {'topic_id': topic_id_map['Війна'], 'value': 'пенсіонери'},
            {'topic_id': topic_id_map['Війна'], 'value': 'Сергій Рахманін'},
            {'topic_id': topic_id_map['Війна'], 'value': 'CNN'},
            {'topic_id': topic_id_map['Війна'], 'value': 'ядерна зброя'},
            {'topic_id': topic_id_map['Війна'], 'value': 'єнс столтенберг'},
            {'topic_id': topic_id_map['Війна'], 'value': 'новини дніпропетровської області'},
            {'topic_id': topic_id_map['Війна'], 'value': 'Дмитро Лубінець'},
            {'topic_id': topic_id_map['Війна'], 'value': 'новини запоріжжя'},
            {'topic_id': topic_id_map['Війна'], 'value': 'маша єфросиніна'},
            {'topic_id': topic_id_map['Війна'], 'value': 'новини Дніпра'},
            {'topic_id': topic_id_map['Війна'], 'value': 'харківська область'},
            {'topic_id': topic_id_map['Війна'], 'value': 'харків'},
            {'topic_id': topic_id_map['Війна'], 'value': 'Бурятія'},
            {'topic_id': topic_id_map['Війна'], 'value': 'лікарі'},
            {'topic_id': topic_id_map['Війна'], 'value': 'новини сумщини'},
            {'topic_id': topic_id_map['Війна'], 'value': 'евакуація'},
            {'topic_id': topic_id_map['Війна'], 'value': 'новини сумської області'},
            {'topic_id': topic_id_map['Війна'], 'value': 'польща'},
            {'topic_id': topic_id_map['Війна'], 'value': 'злата огнєвіч'},
            {'topic_id': topic_id_map['Війна'], 'value': 'чернігів'},
            {'topic_id': topic_id_map['Війна'], 'value': 'вибухи'},
            {'topic_id': topic_id_map['Війна'], 'value': 'страта'},
            {'topic_id': topic_id_map['Війна'], 'value': 'фронт'},
            {'topic_id': topic_id_map['Війна'], 'value': 'Alyona Alyona'},
            {'topic_id': topic_id_map['Війна'], 'value': 'полтава'},
            {'topic_id': topic_id_map['Війна'], 'value': 'паляниця'},
            {'topic_id': topic_id_map['Війна'], 'value': 'зерновоз'},
            {'topic_id': topic_id_map['Війна'], 'value': 'фсб'},
            {'topic_id': topic_id_map['Війна'], 'value': 'коваленко'},
            {'topic_id': topic_id_map['Війна'], 'value': 'безпілотник'},
            {'topic_id': topic_id_map['Війна'], 'value': 'мобілізація'},
            {'topic_id': topic_id_map['Війна'], 'value': 'Ігор Клименко'},
            {'topic_id': topic_id_map['Війна'], 'value': 'Генштаб'},
            {'topic_id': topic_id_map['Війна'], 'value': 'сумська область'},
            {'topic_id': topic_id_map['Війна'], 'value': 'воєнні злочини'},
            {'topic_id': topic_id_map['Війна'], 'value': 'поліція'},
            {'topic_id': topic_id_map['Війна'], 'value': 'надя дорофєєва'},
            {'topic_id': topic_id_map['Війна'], 'value': 'Рамштайн'},
            {'topic_id': topic_id_map['Війна'], 'value': 'Селідове'},
            {'topic_id': topic_id_map['Війна'], 'value': 'бронювання'},
            {'topic_id': topic_id_map['Війна'], 'value': 'курахове'},
            {'topic_id': topic_id_map['Війна'], 'value': 'Валерій Залужний'},
            {'topic_id': topic_id_map['Війна'], 'value': 'ссо'},
            {'topic_id': topic_id_map['Війна'], 'value': 'журналісти'},
            {'topic_id': topic_id_map['Війна'], 'value': 'оточення'},
            {'topic_id': topic_id_map['Війна'], 'value': 'Олег Синєгубов'},
            {'topic_id': topic_id_map['Війна'], 'value': 'ППО'},
            {'topic_id': topic_id_map['Війна'], 'value': 'іран'},
            {'topic_id': topic_id_map['Війна'], 'value': 'ракета'},
            {'topic_id': topic_id_map['Війна'], 'value': 'олександр коваленко'},
            {'topic_id': topic_id_map['Війна'], 'value': 'сирський'},
            {'topic_id': topic_id_map['Війна'], 'value': 'сша'},
            {'topic_id': topic_id_map['Війна'], 'value': 'літак'},
            {'topic_id': topic_id_map['Війна'], 'value': 'лікарня'},
            {'topic_id': topic_id_map['Війна'], 'value': 'володимир зеленський'},
            {'topic_id': topic_id_map['Війна'], 'value': 'Курськ'},
            {'topic_id': topic_id_map['Війна'], 'value': 'новини Кривого Рогу'},
            {'topic_id': topic_id_map['Війна'], 'value': 'окупація'},
            {'topic_id': topic_id_map['Війна'], 'value': 'донбас'},
            {'topic_id': topic_id_map['Війна'], 'value': 'бомба'},
            {'topic_id': topic_id_map['Війна'], 'value': 'деокупація'},
            {'topic_id': topic_id_map['Війна'], 'value': 'новини Чернігова'},
            {'topic_id': topic_id_map['Війна'], 'value': 'олег жданов'},
            {'topic_id': topic_id_map['Війна'], 'value': 'постраждалі'},
            {'topic_id': topic_id_map['Війна'], 'value': 'харківщина'},
            {'topic_id': topic_id_map['Війна'], 'value': 'ветерани'},
            {'topic_id': topic_id_map['Війна'], 'value': 'НАТО'},
            {'topic_id': topic_id_map['Війна'], 'value': 'росія'},
            {'topic_id': topic_id_map['Війна'], 'value': 'електростанція'},
            {'topic_id': topic_id_map['Війна'], 'value': 'Суми'},
            {'topic_id': topic_id_map['Війна'], 'value': 'новини Київської області'},
            {'topic_id': topic_id_map['Війна'], 'value': 'війна'},
            {'topic_id': topic_id_map['Війна'], 'value': 'тимчасово окуповані території'},
            {'topic_id': topic_id_map['Війна'], 'value': 'дрони'},
            {'topic_id': topic_id_map['Війна'], 'value': 'ракетний удар'},
            {'topic_id': topic_id_map['Війна'], 'value': 'тверська область'},
            {'topic_id': topic_id_map['Війна'], 'value': 'командир'},
            {'topic_id': topic_id_map['Війна'], 'value': 'ЗСУ'},
            {'topic_id': topic_id_map['Війна'], 'value': 'Краматорськ'},
            {'topic_id': topic_id_map['Війна'], 'value': 'донецька область'},
            {'topic_id': topic_id_map['Війна'], 'value': 'Часів Яр'},
            {'topic_id': topic_id_map['Війна'], 'value': 'вибух'},
            {'topic_id': topic_id_map['Війна'], 'value': 'Донеччина'},
            {'topic_id': topic_id_map['Війна'], 'value': 'полонені'},
            {'topic_id': topic_id_map['Війна'], 'value': 'паспорт'},
            {'topic_id': topic_id_map['Війна'], 'value': 'ірина сопонару'},
            {'topic_id': topic_id_map['Війна'], 'value': 'фехтування'},
            {'topic_id': topic_id_map['Війна'], 'value': 'Дніпро'},
            {'topic_id': topic_id_map['Війна'], 'value': 'обстріл'},
            {'topic_id': topic_id_map['Війна'], 'value': 'пожежа'},
            {'topic_id': topic_id_map['Війна'], 'value': 'селидове'},
            {'topic_id': topic_id_map['Війна'], 'value': 'Херсон'},
            {'topic_id': topic_id_map['Війна'], 'value': 'арешт'},
            {'topic_id': topic_id_map['Війна'], 'value': 'розстріл'},
            {'topic_id': topic_id_map['Війна'], 'value': 'Patriot'},
            {'topic_id': topic_id_map['Війна'], 'value': 'успіхи'},
            {'topic_id': topic_id_map['Війна'], 'value': 'Покровськ'},
            {'topic_id': topic_id_map['Війна'], 'value': 'Михайло Подоляк'},
            {'topic_id': topic_id_map['Війна'], 'value': 'новини донеччини'},
            {'topic_id': topic_id_map['Війна'], 'value': 'тривога'},
            {'topic_id': topic_id_map['Війна'], 'value': 'Путін'},
            {'topic_id': topic_id_map['Війна'], 'value': 'загиблі'},
            {'topic_id': topic_id_map['Війна'], 'value': 'військовий'},
            {'topic_id': topic_id_map['Війна'], 'value': 'уряд'},
            {'topic_id': topic_id_map['Війна'], 'value': 'винищувач'},
            {'topic_id': topic_id_map['Війна'], 'value': 'контрнаступ'},
            {'topic_id': topic_id_map['Війна'], 'value': 'україна'},
            {'topic_id': topic_id_map['Війна'], 'value': 'андрій бєдняков'},
            {'topic_id': topic_id_map['Війна'], 'value': 'мзс'},
            {'topic_id': topic_id_map['Війна'], 'value': 'верховна рада'},
            {'topic_id': topic_id_map['Війна'], 'value': 'окупанти'},
            {'topic_id': topic_id_map['Війна'], 'value': 'олена мозгова'},
            {'topic_id': topic_id_map['Війна'], 'value': 'Полтавська область'},
            {'topic_id': topic_id_map['Війна'], 'value': 'Вугледар'},
            {'topic_id': topic_id_map['Війна'], 'value': 'жорін'},
            {'topic_id': topic_id_map['Війна'], 'value': 'новини дніпропетровщини'},
            {'topic_id': topic_id_map['Війна'], 'value': 'настя каменських'},
            {'topic_id': topic_id_map['Війна'], 'value': 'новини Києва'},
            {'topic_id': topic_id_map['Війна'], 'value': 'новини Одещини'},
            {'topic_id': topic_id_map['Війна'], 'value': 'росіяни'},
            {'topic_id': topic_id_map['Війна'], 'value': 'Херсонська область'},
            {'topic_id': topic_id_map['Війна'], 'value': 'нікополь'},
            {'topic_id': topic_id_map['Війна'], 'value': 'ллойд остін'},
            {'topic_id': topic_id_map['Війна'], 'value': 'житло'},
            {'topic_id': topic_id_map['Війна'], 'value': 'Румунія'},
            {'topic_id': topic_id_map['Війна'], 'value': 'загибель'},
            {'topic_id': topic_id_map['Війна'], 'value': 'новини харкова'},
            {'topic_id': topic_id_map['Війна'], 'value': 'втрати'},
            {'topic_id': topic_id_map['Війна'], 'value': 'дніпропетровська область'},
            {'topic_id': topic_id_map['Світ'], 'value': 'москва'},
            {'topic_id': topic_id_map['Світ'], 'value': 'львів'},
            {'topic_id': topic_id_map['Світ'], 'value': 'сектор Газа'},
            {'topic_id': topic_id_map['Світ'], 'value': 'дональд туск'},
            {'topic_id': topic_id_map['Світ'], 'value': 'відбудова'},
            {'topic_id': topic_id_map['Світ'], 'value': 'Кримський міст'},
            {'topic_id': topic_id_map['Світ'], 'value': 'енергоресурси'},
            {'topic_id': topic_id_map['Світ'], 'value': 'аеродром'},
            {'topic_id': topic_id_map['Світ'], 'value': 'південна корея'},
            {'topic_id': topic_id_map['Світ'], 'value': 'Намібія'},
            {'topic_id': topic_id_map['Світ'], 'value': 'газ'},
            {'topic_id': topic_id_map['Світ'], 'value': 'космос'},
            {'topic_id': topic_id_map['Світ'], 'value': 'ядерна зброя'},
            {'topic_id': topic_id_map['Світ'], 'value': 'звук'},
            {'topic_id': topic_id_map['Світ'], 'value': 'цікавинки'},
            {'topic_id': topic_id_map['Світ'], 'value': 'диверсії'},
            {'topic_id': topic_id_map['Світ'], 'value': 'вірменія'},
            {'topic_id': topic_id_map['Світ'], 'value': 'римський статут'},
            {'topic_id': topic_id_map['Світ'], 'value': 'мі-8'},
            {'topic_id': topic_id_map['Світ'], 'value': 'ізраїль'},
            {'topic_id': topic_id_map['Світ'], 'value': 'світ'},
            {'topic_id': topic_id_map['Світ'], 'value': 'Telegram'},
            {'topic_id': topic_id_map['Світ'], 'value': 'руйнування'},
            {'topic_id': topic_id_map['Світ'], 'value': 'спецпідрозділ'},
            {'topic_id': topic_id_map['Світ'], 'value': 'Дуров'},
            {'topic_id': topic_id_map['Світ'], 'value': 'польща'},
            {'topic_id': topic_id_map['Світ'], 'value': 'Кремль'},
            {'topic_id': topic_id_map['Світ'], 'value': 'вибухи'},
            {'topic_id': topic_id_map['Світ'], 'value': 'біженці'},
            {'topic_id': topic_id_map['Світ'], 'value': 'ГЕС'},
            {'topic_id': topic_id_map['Світ'], 'value': 'страта'},
            {'topic_id': topic_id_map['Світ'], 'value': 'австрія'},
            {'topic_id': topic_id_map['Світ'], 'value': 'Азербайджан'},
            {'topic_id': topic_id_map['Світ'], 'value': 'відстріл'},
            {'topic_id': topic_id_map['Світ'], 'value': 'Анналена Бербок'},
            {'topic_id': topic_id_map['Світ'], 'value': 'пункт пропуску'},
            {'topic_id': topic_id_map['Світ'], 'value': 'nasa'},
            {'topic_id': topic_id_map['Світ'], 'value': 'страйк'},
            {'topic_id': topic_id_map['Світ'], 'value': 'стівен кінг'},
            {'topic_id': topic_id_map['Світ'], 'value': 'безпілотник'},
            {'topic_id': topic_id_map['Світ'], 'value': 'повінь'},
            {'topic_id': topic_id_map['Світ'], 'value': 'хакери'},
            {'topic_id': topic_id_map['Світ'], 'value': 'естонія'},
            {'topic_id': topic_id_map['Світ'], 'value': 'пранкери'},
            {'topic_id': topic_id_map['Світ'], 'value': 'Twitter'},
            {'topic_id': topic_id_map['Світ'], 'value': 'радослав сікорський'},
            {'topic_id': topic_id_map['Світ'], 'value': 'КНДР'},
            {'topic_id': topic_id_map['Світ'], 'value': 'заручники'},
            {'topic_id': topic_id_map['Світ'], 'value': 'китай'},
            {'topic_id': topic_id_map['Світ'], 'value': 'санкції'},
            {'topic_id': topic_id_map['Світ'], 'value': 'євросоюз'},
            {'topic_id': topic_id_map['Світ'], 'value': 'письменник'},
            {'topic_id': topic_id_map['Світ'], 'value': 'F-16'},
            {'topic_id': topic_id_map['Світ'], 'value': 'суд'},
            {'topic_id': topic_id_map['Світ'], 'value': 'кордон'},
            {'topic_id': topic_id_map['Світ'], 'value': 'туреччина'},
            {'topic_id': topic_id_map['Світ'], 'value': 'тайвань'},
            {'topic_id': topic_id_map['Світ'], 'value': 'вчений'},
            {'topic_id': topic_id_map['Світ'], 'value': 'аеропорти'},
            {'topic_id': topic_id_map['Світ'], 'value': 'ППО'},
            {'topic_id': topic_id_map['Світ'], 'value': 'іран'},
            {'topic_id': topic_id_map['Світ'], 'value': 'ракета'},
            {'topic_id': topic_id_map['Світ'], 'value': 'відставка'},
            {'topic_id': topic_id_map['Світ'], 'value': 'філіппіни'},
            {'topic_id': topic_id_map['Світ'], 'value': 'польша'},
            {'topic_id': topic_id_map['Світ'], 'value': 'сша'},
            {'topic_id': topic_id_map['Світ'], 'value': 'угорщина'},
            {'topic_id': topic_id_map['Світ'], 'value': 'пар'},
            {'topic_id': topic_id_map['Світ'], 'value': 'Греція'},
            {'topic_id': topic_id_map['Світ'], 'value': 'Британія'},
            {'topic_id': topic_id_map['Світ'], 'value': 'кібератака'},
            {'topic_id': topic_id_map['Світ'], 'value': 'розслідування'},
            {'topic_id': topic_id_map['Світ'], 'value': 'смерть'},
            {'topic_id': topic_id_map['Світ'], 'value': 'володимир зеленський'},
            {'topic_id': topic_id_map['Світ'], 'value': 'Курськ'},
            {'topic_id': topic_id_map['Світ'], 'value': 'голод'},
            {'topic_id': topic_id_map['Світ'], 'value': 'брікс'},
            {'topic_id': topic_id_map['Світ'], 'value': 'білорусь'},
            {'topic_id': topic_id_map['Світ'], 'value': 'ландсбергіс'},
            {'topic_id': topic_id_map['Світ'], 'value': 'нафта'},
            {'topic_id': topic_id_map['Світ'], 'value': 'білуха'},
            {'topic_id': topic_id_map['Світ'], 'value': 'тварини'},
            {'topic_id': topic_id_map['Світ'], 'value': 'гур'},
            {'topic_id': topic_id_map['Світ'], 'value': 'БПЛА'},
            {'topic_id': topic_id_map['Світ'], 'value': 'бавовна'},
            {'topic_id': topic_id_map['Світ'], 'value': 'аварія'},
            {'topic_id': topic_id_map['Світ'], 'value': 'НАТО'},
            {'topic_id': topic_id_map['Світ'], 'value': 'віза'},
            {'topic_id': topic_id_map['Світ'], 'value': 'росія'},
            {'topic_id': topic_id_map['Світ'], 'value': 'електростанція'},
            {'topic_id': topic_id_map['Світ'], 'value': 'астронавти'},
            {'topic_id': topic_id_map['Світ'], 'value': 'вбивство'},
            {'topic_id': topic_id_map['Світ'], 'value': 'війна'},
            {'topic_id': topic_id_map['Світ'], 'value': 'допомога'},
            {'topic_id': topic_id_map['Світ'], 'value': 'МКС'},
            {'topic_id': topic_id_map['Світ'], 'value': 'дрони'},
            {'topic_id': topic_id_map['Світ'], 'value': 'мігранти'},
            {'topic_id': topic_id_map['Світ'], 'value': 'ракетний удар'},
            {'topic_id': topic_id_map['Світ'], 'value': 'ЗСУ'},
            {'topic_id': topic_id_map['Світ'], 'value': 'астероїд'},
            {'topic_id': topic_id_map['Світ'], 'value': 'армія'},
            {'topic_id': topic_id_map['Світ'], 'value': 'посуха'},
            {'topic_id': topic_id_map['Світ'], 'value': 'дмитро кулеба'},
            {'topic_id': topic_id_map['Світ'], 'value': 'франція'},
            {'topic_id': topic_id_map['Світ'], 'value': 'українці'},
            {'topic_id': topic_id_map['Світ'], 'value': 'Грузія'},
            {'topic_id': topic_id_map['Світ'], 'value': 'Чорне море'},
            {'topic_id': topic_id_map['Світ'], 'value': 'переговори'},
            {'topic_id': topic_id_map['Світ'], 'value': 'ілон маск'},
            {'topic_id': topic_id_map['Світ'], 'value': 'держзрада'},
            {'topic_id': topic_id_map['Світ'], 'value': 'сергій лавров'},
            {'topic_id': topic_id_map['Світ'], 'value': 'зґвалтування'},
            {'topic_id': topic_id_map['Світ'], 'value': 'катастрофа'},
            {'topic_id': topic_id_map['Світ'], 'value': 'обстріл'},
            {'topic_id': topic_id_map['Світ'], 'value': 'пожежа'},
            {'topic_id': topic_id_map['Світ'], 'value': 'німеччина'},
            {'topic_id': topic_id_map['Світ'], 'value': 'бразилія'},
            {'topic_id': topic_id_map['Світ'], 'value': 'Міжнародний кримінальний суд'},
            {'topic_id': topic_id_map['Світ'], 'value': 'аеропорт'},
            {'topic_id': topic_id_map['Світ'], 'value': 'Монголія'},
            {'topic_id': topic_id_map['Світ'], 'value': 'арешт'},
            {'topic_id': topic_id_map['Світ'], 'value': 'дикі тварини'},
            {'topic_id': topic_id_map['Світ'], 'value': 'Patriot'},
            {'topic_id': topic_id_map['Світ'], 'value': 'школа'},
            {'topic_id': topic_id_map['Світ'], 'value': 'ультраправі'},
            {'topic_id': topic_id_map['Світ'], 'value': 'Путін'},
            {'topic_id': topic_id_map['Світ'], 'value': 'казахстан'},
            {'topic_id': topic_id_map['Світ'], 'value': 'литва'},
            {'topic_id': topic_id_map['Світ'], 'value': 'Північна Корея'},
            {'topic_id': topic_id_map['Світ'], 'value': 'швейцарія'},
            {'topic_id': topic_id_map['Світ'], 'value': 'відновлення'},
            {'topic_id': topic_id_map['Світ'], 'value': 'Норвегія'},
            {'topic_id': topic_id_map['Світ'], 'value': 'опитування'},
            {'topic_id': topic_id_map['Світ'], 'value': 'винищувач'},
            {'topic_id': topic_id_map['Світ'], 'value': 'звільнення'},
            {'topic_id': topic_id_map['Світ'], 'value': 'АЕС'},
            {'topic_id': topic_id_map['Світ'], 'value': 'україна'},
            {'topic_id': topic_id_map['Світ'], 'value': 'мзс'},
            {'topic_id': topic_id_map['Світ'], 'value': 'МВФ'},
            {'topic_id': topic_id_map['Світ'], 'value': 'хакер'},
            {'topic_id': topic_id_map['Світ'], 'value': 'стрілянина'},
            {'topic_id': topic_id_map['Світ'], 'value': 'позов'},
            {'topic_id': topic_id_map['Світ'], 'value': 'Бєлгород'},
            {'topic_id': topic_id_map['Світ'], 'value': 'Олаф Шольц'},
            {'topic_id': topic_id_map['Світ'], 'value': 'вибори'},
            {'topic_id': topic_id_map['Світ'], 'value': 'Камала гарріс'},
            {'topic_id': topic_id_map['Світ'], 'value': 'авіація'},
            {'topic_id': topic_id_map['Світ'], 'value': 'кит'},
            {'topic_id': topic_id_map['Світ'], 'value': 'електроенергія'},
            {'topic_id': topic_id_map['Світ'], 'value': 'полон'},
            {'topic_id': topic_id_map['Світ'], 'value': 'борис джонсон'},
            {'topic_id': topic_id_map['Світ'], 'value': 'Румунія'},
            {'topic_id': topic_id_map['Світ'], 'value': 'зброя'},
            {'topic_id': topic_id_map['Світ'], 'value': 'дискримінація'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'ніколь кідман'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'Сідні Свіні'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'ярослава магучіх'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'Кендалл Дженнер'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'антоніна хижняк'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'клаудія шиффер'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'Розі Гантінгтон-Вайтлі'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'TikTok'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'Емілі Ратаковскі'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'тоні гаррн'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'джорджина родрігес'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'кейт вінслет'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'Тільда Свінтон'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'Алессандра Амбросіо'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'амаль клуні'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'хоакін фенікс'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'оля цибульська'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'День народження'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'кейт бланшетт'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'Бруклін Бекхем'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'Нікола Пельтц'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'джокер'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'джордж клуні'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'кім кардашян'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'Арабелла Чі'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'сальма гаєк'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'моделі в бікіні'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'наомі кемпбелл'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'тренди'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'аліна байкова'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'дакота джонсон'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'соломія вітвіцька'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'володимир дантес'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'Джуліанна Мур'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'леді гага'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'провокаційний образ'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'сексуальний образ'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'Ізабель Гулар'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'анджеліна джолі'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'гайді клум'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'Демі мур'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'елізабет тейлор'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'стильний образ'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'Венеційський кінофестиваль'},
            {'topic_id': topic_id_map['Шоу-бізнес'], 'value': 'вікторія бекхем'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'даша кацуріна'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'володимир остапчук'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'міша кацурін'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'машуковський'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'маша єфросиніна'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'мохаммад захур'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'харків'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'лідія таран'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'олександр волошин'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'jerry heil'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'анна кошмал'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'даша малахова'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'могилевська'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'Julik'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'Григорій Решетнік'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'аліна гросу'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'анастасія приходько'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'таїсія повалій'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'monatik'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'андрій федінчик'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'артем пивоваров'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'потап'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'надя дорофєєва'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'тіна кароль'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'Вʼячеслав Узелков'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'євген клопотенко'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'Моніка Беллуччі'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'соня плакидюк'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'бред пітт'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'іван люленов'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'лілія ребрик'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'ада роговцева'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'катерина репʼяхова'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'даша астафʼєва'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'ірина федишин'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'андрій дикий'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'A$AP Rocky'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'анна трінчер'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'марія бурмака'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'юлік'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'анна саліванчук'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'володимир зеленський'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'тимур хромаєв'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'євген кошовий'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'ксенія мішина'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'камалія'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'назарій яремчук'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'вєрка сердючка'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'оля цибульська'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'анастасія цимбалару'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'ольга харлан'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'олександра кучеренко'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'Саша Бо'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'винник'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'аліна шаманська'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'Елтон Джон'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'інна мірошниченко'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'анатолій анатоліч'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'варвара кошова'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'володимир дантес'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'дмитро ступка'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'віталій козловський'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'анджеліна джолі'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'олег винник'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'alyosha'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'ольга сумська'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'олена шоптенко'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'оля полякова'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'Тім Бертон'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'тарас тополя'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'наталка денисенко'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'Klavdia Petrivna'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'мурат налчаджиоглу'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'слава дьомін'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'наталка карпа'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'дмитро дікусар'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'павло зібров'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'андрій данилко'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'остап ступка'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'марія яремчук'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'ксенія кошова'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'єлизавета юрушева'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'шеннен догерті'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'Lida Lee'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'олександр скічко'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'олена кравець'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'тимур мірошниченко'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'джамала'},
            {'topic_id': topic_id_map['Гламур'], 'value': 'алла зіневич'},
            {'topic_id': topic_id_map['Київ'], 'value': 'олексій резніков'},
            {'topic_id': topic_id_map['Київ'], 'value': 'безпілотник'},
            {'topic_id': topic_id_map['Київ'], 'value': 'татаров'},
            {'topic_id': topic_id_map['Київ'], 'value': 'метро'},
            {'topic_id': topic_id_map['Київ'], 'value': 'МВС'},
            {'topic_id': topic_id_map['Київ'], 'value': 'мусульмани'},
            {'topic_id': topic_id_map['Київ'], 'value': 'поліція'},
            {'topic_id': topic_id_map['Київ'], 'value': 'ДСНС'},
            {'topic_id': topic_id_map['Київ'], 'value': 'авто'},
            {'topic_id': topic_id_map['Київ'], 'value': 'амброзія'},
            {'topic_id': topic_id_map['Київ'], 'value': 'чеченці'},
            {'topic_id': topic_id_map['Київ'], 'value': 'новини Київської області'},
            {'topic_id': topic_id_map['Київ'], 'value': 'україна'},
            {'topic_id': topic_id_map['Київ'], 'value': 'київська область'},
            {'topic_id': topic_id_map['Київ'], 'value': 'дрони'},
            {'topic_id': topic_id_map['Київ'], 'value': 'автомобіль'},
            {'topic_id': topic_id_map['Київ'], 'value': 'потяг'},
            {'topic_id': topic_id_map['Київ'], 'value': 'ракетний удар'},
            {'topic_id': topic_id_map['Київ'], 'value': 'пістолет'},
            {'topic_id': topic_id_map['Київ'], 'value': 'урядовий квартал'},
            {'topic_id': topic_id_map['Київ'], 'value': 'підпал авто'},
            {'topic_id': topic_id_map['Київ'], 'value': 'стрілянина'},
            {'topic_id': topic_id_map['Київ'], 'value': 'потерпілі'},
            {'topic_id': topic_id_map['Київ'], 'value': 'чорнобильська зона'},
            {'topic_id': topic_id_map['Київ'], 'value': 'Чорнобиль'},
            {'topic_id': topic_id_map['Київ'], 'value': 'ППО'},
            {'topic_id': topic_id_map['Київ'], 'value': 'ракета'},
            {'topic_id': topic_id_map['Київ'], 'value': 'Мусієнко'},
            {'topic_id': topic_id_map['Київ'], 'value': 'новини Києва'},
            {'topic_id': topic_id_map['Київ'], 'value': 'фото'},
            {'topic_id': topic_id_map['Київ'], 'value': 'вибухи'},
            {'topic_id': topic_id_map['Київ'], 'value': 'карантин'},
            {'topic_id': topic_id_map['Київ'], 'value': 'пожежа'},
            {'topic_id': topic_id_map['Київ'], 'value': 'мечеть'},
            {'topic_id': topic_id_map['Київ'], 'value': 'київ'},
            {'topic_id': topic_id_map['Київ'], 'value': 'загибель'},
            {'topic_id': topic_id_map['Київ'], 'value': 'зброя'},
            {'topic_id': topic_id_map['Київ'], 'value': 'підпал'},
            {'topic_id': topic_id_map['Київ'], 'value': 'Сухостій'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'нью-йорк'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'чернігівська область'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'львів'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'денис шмигаль'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Рада'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'позбавлення прав'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'кадрові зміни'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Нацбанк'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Торецьк'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'газ'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'енергоблок'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'ядерна зброя'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'новини Рівного'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'ірина фаріон'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'партія регіонів'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Дмитро Лубінець'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Андрій Єрмак'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'кабмін'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'екологія'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'омбудсман'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'запорізька аес'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'нестор шуфрич'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'харківська область'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'харків'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'укрзалізниця'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'танк'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'діти'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'автомобіль'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'новини сумщини'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'підозрюваний'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'забруднення'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'втеча'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'джо байден'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'кіберзлочинність'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'чехія'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'евакуація'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'новини сумської області'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'боржники'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'ірина верещук'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Рафаель Гроссі'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'новини Миколаєва'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'ДПСУ'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'дитяче харчування'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'аліменти'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Кремль'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'чернігів'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'вибухи'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'енергетика'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'сексуальне насильство'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'сейм'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'кіберзахист'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'маршрутка'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'вересень'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'фронт'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'гладкий'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'слуга народу'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'дтп'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'обшуки'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'полтава'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'воєнний злочин'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'медики'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'джастін трюдо'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'СІЗО'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'ізолятор'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'погрози'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'зерновоз'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'волинь'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'фсб'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Івано-Франківськ'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Углава'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'кропивницький'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'безпілотник'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'мобілізація'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'ірпінь'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'новини маріуполя'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Генштаб'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'сумська область'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'військова техніка'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'фонд держмайна'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'ольга стефанішина'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'графік'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'пальмова олія'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Десна'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'поліція'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'водяне'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'прокуратура'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'зерно'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Рамштайн'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'кинджал'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'денис малюська'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'новини Харькова'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'готівка'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Валерій Залужний'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'руслан стефанчук'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'новини чернівців'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'екіпаж'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'заес'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'котел'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'новини Київщини'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'ФОП'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'давид арахамія'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'коваль'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'опу'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'F-16'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'суд'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'вертоліт'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'ТЦК'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'атаки'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'МЗС України'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'кордон'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'гривня'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'НАБУ'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'карти Таро'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'миколаївська область'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Рустем Умєров'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Нова пошта'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'граната'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'кіберзлочинці'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'водійське посвідчення'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'вища освіта'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'ППО'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'поїзди'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'ракета'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'відставка'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'польша'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'сша'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Енергоатом'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'ворог'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'зміни'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'залізниця'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'сирський'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'посилання'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'дружба'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'новини волині'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'повітряна тривога'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Бюджет'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'НП'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'новини Житомира'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Генпрокуратура'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'літак'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'захист'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'навчальний рік'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'азов'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'освіта'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'володимир зеленський'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'смерть'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'знаки зодіаку'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Курськ'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'уламок'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'повістка'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'окупація'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'донбас'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'білорусь'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'чутки'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'розбився'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'бомба'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'новини Чернігова'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'стрілець'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'гроші'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Крим'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'мор риби'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'маріуполь'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'погода'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'авіакатастрофа'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'електрика'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'ветерани'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'росія'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'аварія'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'зима'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'ДБР'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'пілоти'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Суми'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'війна'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'допомога'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'новини Київської області'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'вбивство'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'енергосистема'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'хабар'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'дрони'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'жкх'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'перекази'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'землетрус'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'підготовка'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'корупція'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'ракетний удар'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'ЗСУ'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'монета'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'вибух'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'новини Київ'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'донецька область'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'поранення'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'експерт'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'макіївка'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'полонені'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'похолодання'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'магате'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'міністерство юстиції'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'дмитро кулеба'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'військовозобов’язані'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'спроба самогубства'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'погода в україні'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'указ'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Луцьк'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'саміт'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'шахраї'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'переговори'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Ірландія'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'артем дмитрук'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'заборона'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Дніпро'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Єрмак'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'відстрочка'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'обстріл'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'пожежа'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'новини вінницької області'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Міжнародний кримінальний суд'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Херсон'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'курс валют'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'дельфін'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Монголія'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'суїцид'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Закарпаття'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'премія'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'німеччина'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Шуфрич'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'розстріл'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Міноборони'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'школа'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'астрологія езотерика'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'технології'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Покровськ'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Південноукраїнська АЕС'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'фейки'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Михайло Подоляк'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'новини донеччини'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Укренерго'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'тривога'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Путін'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'гороскоп'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Сибіга'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'синоптик'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'загиблі'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Держприкордонслужба'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'військовий'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'уряд'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'звільнення'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'загинули'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'диверсія'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Укрпошта'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'АЕС'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Молдова'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'україна'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'ВЛК'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'партизани'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'сумщина'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'мзс'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'адвокат'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Павлоград'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'гелікоптер'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'канада'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'СБУ'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'річка'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'верховна рада'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'ДТЕК'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'область'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'окупанти'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'долар'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'відключення світла'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Полтавська область'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'нідерланди'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'злотий'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'міська рада'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'жорін'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'євро'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'стрілянина'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Дія'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'школяри'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'новини Києва'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'фото'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'ту-95мс'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Олаф Шольц'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'росіяни'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'прогноз погоди'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'суспільство'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'авіація'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'олександр дубінський'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'скандал'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'спека'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'НБУ'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'заява'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'нікополь'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'комунальні послуги'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'полон'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'електроенергія'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'Румунія'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'зброя'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'новини харкова'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'втрати'},
            {'topic_id': topic_id_map['Укрaїнa'], 'value': 'дніпропетровська область'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'львів'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'дональд туск'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'новини Львова'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'варшава'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'вісла'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'новини Рівного'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'цікавинки'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'новини запоріжжя'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'копійка'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'злива'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'нестор шуфрич'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'транспорт'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'харків'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'втеча'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'джо байден'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'евакуація'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'польща'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'енергетика'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'вересень'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'полтава'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'медики'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'Київський метрополітен'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'днк'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'безпілотник'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'мобілізація'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'іспит'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'бійка'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'вітер'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'дитсадок'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'Рамштайн'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'бронювання'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'кинджал'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'дмитро гордон'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'провидиця'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'майно'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'євросоюз'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'F-16'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'заморозки'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'суд'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'радіація'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'станції метро'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'кордон'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'коломойський'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'Рустем Умєров'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'виплати'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'водійське посвідчення'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'іран'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'ракета'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'оон'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'сша'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'паркінг'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'осінь'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'пошук'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'Британія'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'київ'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'навчальний рік'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'зміни клімату'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'володимир зеленський'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'Курськ'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'мирні переговори'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'годинники'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'ігор коломойський'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'білорусь'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'волонтер'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'гроші'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'погода'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'зниклі безвісті'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'росія'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'Суми'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'війна'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'МКС'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'замах'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'синоптики'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'дрони'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'готель'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'ракетний удар'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'ЗСУ'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'монета'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'Часів Яр'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'Донеччина'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'дмитро кулеба'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'українці'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'артем дмитрук'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'Дніпро'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'астрологія'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'обстріл'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'пожежа'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'німеччина'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'Херсон'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'курс валют'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'селидове'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'Монголія'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'школа'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'Покровськ'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'метро'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'новини донеччини'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'Укренерго'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'Путін'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'казахстан'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'медведчук'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'Одеса'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'автобус'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'АЕС'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'україна'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'танці'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'нардеп'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'долар'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'дністер'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'відключення світла'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'похорон'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'євро'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'стрілянина'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'чорнобильська зона'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'атлантичний океан'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'новини Києва'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'росіяни'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'вибори'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'спека'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'ллойд остін'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'електроенергія'},
            {'topic_id': topic_id_map['Ексклюзив ТСН'], 'value': 'зброя'},
            {'topic_id': topic_id_map['Зірки'], 'value': 'норвезькі монархи'},
            {'topic_id': topic_id_map['Зірки'], 'value': 'принц вільям'},
            {'topic_id': topic_id_map['Зірки'], 'value': 'королева Камілла'},
            {'topic_id': topic_id_map['Зірки'], 'value': 'принцеса Беатріс'},
            {'topic_id': topic_id_map['Зірки'], 'value': 'король Чарльз III'},
            {'topic_id': topic_id_map['Зірки'], 'value': 'принцеса євгенія'},
            {'topic_id': topic_id_map['Зірки'], 'value': 'принц філіп'},
            {'topic_id': topic_id_map['Зірки'], 'value': 'принцеса Марта Луїза'},
            {'topic_id': topic_id_map['Зірки'], 'value': 'британські монархи'},
            {'topic_id': topic_id_map['Зірки'], 'value': 'принц гаррі'},
            {'topic_id': topic_id_map['Зірки'], 'value': 'Сара Йоркська'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'монако'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'кронпринц даніель'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'королева Камілла'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'принцеса Маргарет'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'олена Зеленська'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'йорданські монархи'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'єва лонгорія'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'принц едвард'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'іспанські монархи'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'новини Львова'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'принц Ендрю'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'Чарльз Спенсер'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'принцеса Анна'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'принц гаррі'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'бельгійські монархи'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'нідерландські монархи'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'королева ранія'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'королева Максима'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'королева Мері'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'принц чарльз'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'принцеса беатрікс'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'кейт міддлтон'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'королева Летиція'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'принцесса Анна'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'Зара Тіндалл'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'ольга харлан'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'кронпринцеса Вікторія'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'король Георг VI'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'ракетний удар'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'заручини'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'королева єлизавета II'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'король Чарльз III'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'Лора Лопес'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'княгиня Шарлін'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'королева Матильда'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'день в історії'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'Том Паркер Боулз'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'принцеса софія'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'принцеса діана'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'королева Маргрете II'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'Сара Йоркська'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'принц вільям'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'принц Крістіан'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'данські монархи'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'князь Альбер II'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'Еллі Голдінг'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'Амелія Спенсер'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'шведські монархи'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'британські монархи'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'принц Карл Філіп'},
            {'topic_id': topic_id_map['Суспільство'], 'value': 'королева Сільвія'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'археологія'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'астролог'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'кохання'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'Венесуела'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'Австралія'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'шахрайство'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'Путін'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'тварини'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'тест'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'цікавинки'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'індія'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'війна'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'китай'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'світ'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'відкриття'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'вʼєтнам'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'ящірка'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'вчені'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'таїланд'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'стосунки'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'здоровʼя'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'кіт'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'франція'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'розкопки'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'екстрасенс'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'сша'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'залізниця'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'мексика'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'пар'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'Британія'},
            {'topic_id': topic_id_map['Цікaвинки'], 'value': 'дикі тварини'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'пальне'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'економіка'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'нафтогаз'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'ціна'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'Нацбанк'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'газ'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'гроші'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'ціни'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'комуналка'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'магазин'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'державний борг'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'ФОП'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'україна'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'впо'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'автогаз'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'банк'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'паливо'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'Данило Гетманцев'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'гривня'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'відключення світла'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'долар'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'злотий'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'виплати'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'борги'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'євро'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'бензин'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'енергетика'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'акциз'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'НБУ'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'кредити'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'курс валют'},
            {'topic_id': topic_id_map['Гроші'], 'value': 'приватизація'},
            {'topic_id': topic_id_map['Наука та IT'], 'value': 'скафандр'},
            {'topic_id': topic_id_map['Наука та IT'], 'value': 'місія'},
            {'topic_id': topic_id_map['Наука та IT'], 'value': 'вчені'},
            {'topic_id': topic_id_map['Наука та IT'], 'value': 'всесвіт'},
            {'topic_id': topic_id_map['Наука та IT'], 'value': 'земля'},
            {'topic_id': topic_id_map['Наука та IT'], 'value': 'звʼязок'},
            {'topic_id': topic_id_map['Наука та IT'], 'value': 'астронавти'},
            {'topic_id': topic_id_map['Наука та IT'], 'value': 'супутник'},
            {'topic_id': topic_id_map['Наука та IT'], 'value': 'ізраїль'},
            {'topic_id': topic_id_map['Наука та IT'], 'value': 'наука'},
            {'topic_id': topic_id_map['Наука та IT'], 'value': 'торнадо'},
            {'topic_id': topic_id_map['Наука та IT'], 'value': 'космос'},
            {'topic_id': topic_id_map['Наука та IT'], 'value': 'nasa'},
            {'topic_id': topic_id_map['Наука та IT'], 'value': 'місяць'},
            {'topic_id': topic_id_map['Наука та IT'], 'value': 'галактика'},
            {'topic_id': topic_id_map['Наука та IT'], 'value': 'цікавинки'},
            {'topic_id': topic_id_map['Наука та IT'], 'value': '4G-зв’язок'},
            {'topic_id': topic_id_map['Здоровий спосіб життя'], 'value': 'ківі'},
            {'topic_id': topic_id_map['Здоровий спосіб життя'], 'value': 'поради'},
            {'topic_id': topic_id_map['Здоровий спосіб життя'], 'value': 'здоровʼя'},
            {'topic_id': topic_id_map['Дім'], 'value': 'лимон'},
            {'topic_id': topic_id_map['Дім'], 'value': 'Петрушка'},
            {'topic_id': topic_id_map['Дім'], 'value': 'прибирання'},
            {'topic_id': topic_id_map['Дім'], 'value': 'город'},
            {'topic_id': topic_id_map['Дім'], 'value': 'добрива'},
            {'topic_id': topic_id_map['Дім'], 'value': 'дім'},
            {'topic_id': topic_id_map['Дім'], 'value': 'кріп'},
            {'topic_id': topic_id_map['Дім'], 'value': 'сад'},
            {'topic_id': topic_id_map['Дім'], 'value': 'поради'},
            {'topic_id': topic_id_map['Дім'], 'value': 'прання'},
            {'topic_id': topic_id_map['Дім'], 'value': 'садівництво'},
            {'topic_id': topic_id_map['Дім'], 'value': 'подушки'},
            {'topic_id': topic_id_map['Дім'], 'value': 'рослини'},
            {'topic_id': topic_id_map['Дім'], 'value': 'кухня'},
            {'topic_id': topic_id_map['Схуднення'], 'value': 'поради'},
            {'topic_id': topic_id_map['Актуальна тема'], 'value': 'шкіра'},
            {'topic_id': topic_id_map['Актуальна тема'], 'value': 'вечеря'},
            {'topic_id': topic_id_map['Актуальна тема'], 'value': 'здоровʼя'},
            {'topic_id': topic_id_map['Актуальна тема'], 'value': 'здоровʼя'},
            {'topic_id': topic_id_map['Актуальна тема'], 'value': 'біль'},
            {'topic_id': topic_id_map['Актуальна тема'], 'value': 'поради'},
            {'topic_id': topic_id_map['Актуальна тема'], 'value': 'спорт'},
            {'topic_id': topic_id_map['Актуальна тема'], 'value': 'харчування'},
            {'topic_id': topic_id_map['Актуальна тема'], 'value': 'кавун'},
            {'topic_id': topic_id_map['Актуальна тема'], 'value': 'Катерина Толстікова'},
            {'topic_id': topic_id_map['Актуальна тема'], 'value': 'кашель'},
            {'topic_id': topic_id_map['Актуальна тема'], 'value': 'схуднення'},
            {'topic_id': topic_id_map['Актуальна тема'], 'value': 'цукор'},
            {'topic_id': topic_id_map['Рецепти'], 'value': 'смузі'},
            {'topic_id': topic_id_map['Рецепти'], 'value': 'рецепт'},
            {'topic_id': topic_id_map['Рецепти'], 'value': 'авокадо'},
            {'topic_id': topic_id_map['Рецепти'], 'value': 'поради'},
            {'topic_id': topic_id_map['Рецепти'], 'value': 'страви'},
            {'topic_id': topic_id_map['Рецепти'], 'value': 'овочі'},
            {'topic_id': topic_id_map['Рецепти'], 'value': 'рецепти'},
            {'topic_id': topic_id_map['Рецепти'], 'value': 'кухня'},
            {'topic_id': topic_id_map['Астрологія'], 'value': 'астропрогноз'},
            {'topic_id': topic_id_map['Астрологія'], 'value': 'знаки зодіаку'},
            {'topic_id': topic_id_map['Астрологія'], 'value': 'астролог'},
            {'topic_id': topic_id_map['Астрологія'], 'value': 'карти Таро'},
            {'topic_id': topic_id_map['Астрологія'], 'value': 'молодик'},
            {'topic_id': topic_id_map['Астрологія'], 'value': 'діва'},
            {'topic_id': topic_id_map['Астрологія'], 'value': 'руни'},
            {'topic_id': topic_id_map['Астрологія'], 'value': 'астрологія'},
            {'topic_id': topic_id_map['Астрологія'], 'value': 'езотерика'},
            {'topic_id': topic_id_map['Астрологія'], 'value': 'війна'},
            {'topic_id': topic_id_map['Астрологія'], 'value': 'україна'},
            {'topic_id': topic_id_map['Астрологія'], 'value': 'гороскоп'},
            {'topic_id': topic_id_map['Астрологія'], 'value': 'Уран'},
            {'topic_id': topic_id_map['Астрологія'], 'value': 'ретроградність'},
            {'topic_id': topic_id_map['Астрологія'], 'value': 'перемога'},
            {'topic_id': topic_id_map['Астрологія'], 'value': 'ретроградний меркурій'},
            {'topic_id': topic_id_map['Астрологія'], 'value': 'астрологія езотерика'},
            {'topic_id': topic_id_map['Різне'], 'value': 'знаки зодіаку'},
            {'topic_id': topic_id_map['Різне'], 'value': 'квіти'},
            {'topic_id': topic_id_map['Різне'], 'value': 'церковне свято'},
            {'topic_id': topic_id_map['Різне'], 'value': 'город'},
            {'topic_id': topic_id_map['Різне'], 'value': 'поради'},
            {'topic_id': topic_id_map['Різне'], 'value': 'авто'},
            {'topic_id': topic_id_map['Різне'], 'value': 'тест'},
            {'topic_id': topic_id_map['Різне'], 'value': 'день знань'},
            {'topic_id': topic_id_map['Різне'], 'value': 'джинси'},
            {'topic_id': topic_id_map['Різне'], 'value': 'логіка'},
            {'topic_id': topic_id_map['Різне'], 'value': 'перше вересня'},
            {'topic_id': topic_id_map['Різне'], 'value': 'вино'},
            {'topic_id': topic_id_map['Різне'], 'value': 'автівки'},
            {'topic_id': topic_id_map['Різне'], 'value': 'одяг'},
            {'topic_id': topic_id_map['Різне'], 'value': 'добрива'},
            {'topic_id': topic_id_map['Різне'], 'value': 'автомобіль'},
            {'topic_id': topic_id_map['Різне'], 'value': 'Гіацинт'},
            {'topic_id': topic_id_map['Різне'], 'value': 'купівля'},
            {'topic_id': topic_id_map['Різне'], 'value': 'стрижка'},
            {'topic_id': topic_id_map['Різне'], 'value': 'тести'},
            {'topic_id': topic_id_map['Різне'], 'value': 'тренди'},
            {'topic_id': topic_id_map['Різне'], 'value': 'поради водіям'},
            {'topic_id': topic_id_map['Різне'], 'value': 'помідори'},
            {'topic_id': topic_id_map['Різне'], 'value': 'психологія'},
            {'topic_id': topic_id_map['Різне'], 'value': 'зачіска'},
            {'topic_id': topic_id_map['Різне'], 'value': 'лайфхаки'},
            {'topic_id': topic_id_map['Різне'], 'value': 'народні прикмети'},
            {'topic_id': topic_id_map['Різне'], 'value': 'рецепт'},
            {'topic_id': topic_id_map['Різне'], 'value': 'українська мова'},
            {'topic_id': topic_id_map['Різне'], 'value': 'дтп'},
            {'topic_id': topic_id_map['Різне'], 'value': 'стрижки'},
            {'topic_id': topic_id_map['Різне'], 'value': 'день ангела'},
            {'topic_id': topic_id_map['Різне'], 'value': 'тривожність'},
            {'topic_id': topic_id_map['Різне'], 'value': 'чорнобривці'},
            {'topic_id': topic_id_map['Зброя'], 'value': 'БПЛА'},
            {'topic_id': topic_id_map['Зброя'], 'value': 'сша'},
            {'topic_id': topic_id_map['Зброя'], 'value': 'росія'},
            {'topic_id': topic_id_map['Зброя'], 'value': 'Михайло Подоляк'},
            {'topic_id': topic_id_map['Зброя'], 'value': 'війна'},
            {'topic_id': topic_id_map['Зброя'], 'value': 'україна'},
            {'topic_id': topic_id_map['Зброя'], 'value': 'іран'},
            {'topic_id': topic_id_map['Зброя'], 'value': 'ППО'},
            {'topic_id': topic_id_map['Зброя'], 'value': 'ракета'},
            {'topic_id': topic_id_map['Зброя'], 'value': 'дрони'},
            {'topic_id': topic_id_map['Зброя'], 'value': 'Румунія'},
            {'topic_id': topic_id_map['Зброя'], 'value': 'зброя'},
            {'topic_id': topic_id_map['Корисні статті'], 'value': 'діти'},
            {'topic_id': topic_id_map['Корисні статті'], 'value': 'секрети молодості'},
            {'topic_id': topic_id_map['Корисні статті'], 'value': 'здоровʼя'},
            {'topic_id': topic_id_map['Корисні статті'], 'value': 'психологія'},
            {'topic_id': topic_id_map['Діти'], 'value': 'діти'},
            {'topic_id': topic_id_map['Діти'], 'value': 'поради'},
            {'topic_id': topic_id_map['Діти'], 'value': 'здоровʼя'},
            {'topic_id': topic_id_map['Політика'], 'value': 'Курськ'},
            {'topic_id': topic_id_map['Політика'], 'value': 'пальне'},
            {'topic_id': topic_id_map['Політика'], 'value': 'львів'},
            {'topic_id': topic_id_map['Політика'], 'value': 'мобілізація'},
            {'topic_id': topic_id_map['Політика'], 'value': 'фонд держмайна'},
            {'topic_id': topic_id_map['Політика'], 'value': 'Путін'},
            {'topic_id': topic_id_map['Політика'], 'value': 'Рамштайн'},
            {'topic_id': topic_id_map['Політика'], 'value': 'податки'},
            {'topic_id': topic_id_map['Політика'], 'value': 'кабмін'},
            {'topic_id': topic_id_map['Політика'], 'value': 'НАТО'},
            {'topic_id': topic_id_map['Політика'], 'value': 'росія'},
            {'topic_id': topic_id_map['Політика'], 'value': 'Олексій Кулеба'},
            {'topic_id': topic_id_map['Політика'], 'value': 'ізраїль'},
            {'topic_id': topic_id_map['Політика'], 'value': 'заручники'},
            {'topic_id': topic_id_map['Політика'], 'value': 'війна'},
            {'topic_id': topic_id_map['Політика'], 'value': 'україна'},
            {'topic_id': topic_id_map['Політика'], 'value': 'міністерство культури'},
            {'topic_id': topic_id_map['Політика'], 'value': 'верховна рада'},
            {'topic_id': topic_id_map['Політика'], 'value': 'ракетний удар'},
            {'topic_id': topic_id_map['Політика'], 'value': 'джо байден'},
            {'topic_id': topic_id_map['Політика'], 'value': 'МЗС України'},
            {'topic_id': topic_id_map['Політика'], 'value': 'Беньямін Нетаньягу'},
            {'topic_id': topic_id_map['Політика'], 'value': 'ірина верещук'},
            {'topic_id': topic_id_map['Політика'], 'value': 'дмитро кулеба'},
            {'topic_id': topic_id_map['Політика'], 'value': 'сша'},
            {'topic_id': topic_id_map['Політика'], 'value': 'переговори'},
            {'topic_id': topic_id_map['Політика'], 'value': 'Ірландія'},
            {'topic_id': topic_id_map['Політика'], 'value': 'акциз'},
            {'topic_id': topic_id_map['Політика'], 'value': 'артем дмитрук'},
            {'topic_id': topic_id_map['Політика'], 'value': 'дмитро пєсков'},
            {'topic_id': topic_id_map['Політика'], 'value': 'законопроект'},
            {'topic_id': topic_id_map['Політика'], 'value': 'зброя'},
            {'topic_id': topic_id_map['Політика'], 'value': 'лондон'},
            {'topic_id': topic_id_map['Політика'], 'value': 'володимир зеленський'},
            {'topic_id': topic_id_map['Здоров’я'], 'value': 'здоровʼя'},
            {'topic_id': topic_id_map['Здоров’я'], 'value': 'світ'},
            {'topic_id': topic_id_map['Здоров’я'], 'value': 'харчування'},
            {'topic_id': topic_id_map['Здоров’я'], 'value': 'поради'},
            {'topic_id': topic_id_map['Здоров’я'], 'value': 'цікавинки'},
            {'topic_id': topic_id_map['Салон краси'], 'value': 'зачіска'},
            {'topic_id': topic_id_map['Салон краси'], 'value': 'стиль'},
            {'topic_id': topic_id_map['Салон краси'], 'value': 'аромати'},
            {'topic_id': topic_id_map['Салон краси'], 'value': 'ідеї манікюру'},
            {'topic_id': topic_id_map['Салон краси'], 'value': 'поради'},
            {'topic_id': topic_id_map['Салон краси'], 'value': 'пучок'},
            {'topic_id': topic_id_map['Салон краси'], 'value': 'макіяж'},
            {'topic_id': topic_id_map['Салон краси'], 'value': 'мода'},
            {'topic_id': topic_id_map['Салон краси'], 'value': 'краса'},
            {'topic_id': topic_id_map['Львів'], 'value': 'вибухи'},
            {'topic_id': topic_id_map['Львів'], 'value': 'львів'},
            {'topic_id': topic_id_map['Львів'], 'value': 'новини Кривого Рогу'},
            {'topic_id': topic_id_map['Львів'], 'value': 'новини Львова'},
            {'topic_id': topic_id_map['Львів'], 'value': 'львівська область'},
            {'topic_id': topic_id_map['Львів'], 'value': 'новини львівської області'},
            {'topic_id': topic_id_map['Львів'], 'value': 'укрзалізниця'},
            {'topic_id': topic_id_map['Львів'], 'value': 'ППО'},
            {'topic_id': topic_id_map['Львів'], 'value': 'будинки'},
            {'topic_id': topic_id_map['Львів'], 'value': 'ракета'},
            {'topic_id': topic_id_map['Львів'], 'value': 'київська область'},
            {'topic_id': topic_id_map['Львів'], 'value': 'ракетний удар'},
            {'topic_id': topic_id_map['Львів'], 'value': 'володимир зеленський'}
    ]
    )

def downgrade() -> None:
    op.execute("DELETE FROM topic_keywords")
    op.execute("DELETE FROM topics")
